### PR TITLE
Mohammed Al Najar fixing a bug in the timeline "only teachers can view the timeline"

### PR DESCRIPTION
**Pull request by malnajar**
this bug was found in Yousef PR in the routes file **pull request #110** and this was reviewed and approved by me in 17-may (apologize)

### CODE REVIEW

**Comment by JawharBairakdar** [comment]
Are you sure about these changes?

**Comment by M3kH** [comment]
@malnajar Did you try to assign the role teacher to your user? Why does `GET api/users` should be open to everybody? what does break? How can I reproduce?

**Comment by malnajar** [comment]
dude first of all this is the default Yousef add this role by mistake for another reasons, the second thing which the most important that the app will break if you are not teacher which mean no one can use the app except teachers, the last thing you said we should not merge a PR will break the app i don't have any problem with securing the routes but i need a PR can do that without breaking the app

**Comment by malnajar** [comment]
try to use the app, you can not sign in you can not use the app and also if you have a user under student role it is the same

**Pull request closed without merging**
